### ISSUE TITLE
Create list of views

### ISSUE THREAD

**Issue by AleksMorozova** [horba/SWEETer#13]

**Comment by Lytvynenko-Danylo** [comment]
Простите, я не понял задание. Объясните, пожалуйста

**Comment by schect404** [comment]
https://github.com/ISDStudentsInitiative/Jay/wiki/List-of-views--mockup-links

**Comment by schect404** [comment]
https://github.com/ISDStudentsInitiative/Jay/wiki/List-of-views-and-mockups

**Comment by msvaillant** [comment]
done
